language: c

matrix:
  fast_finish: true

dist: focal
services:
  - docker

env:
  global:
    # Coverity token
    - secure: "H21mSRlMhk4BKS0xHZvCFGJxteCP0hRVUxTuNfM2Z9HBsyutuLEYMtViLO86VtM+Tqla3xXPzUdS4ozLwI72Ax/5ZUDXACROj73yW6QhFB5D6rLut12+FjqC7M33Qv2hl0xwgNBmR5dsm1ToP37+Wn+ecJQNvN8fkTXF+HVzOEw="
    # Travis token for mpv.io
    - secure: "nlTVLJK6kRhtXvhKCoJ3YdFGHuKaq/eHowfPw25hqRWuBOZd+HjHY5KIYjV7SxuKFDpJE4GpNcvA3Q31nsqomxpkLYgrwjg6TSazN7ZP+x85ZgV1QGFebrPfGm2n5UR5CAPAwFoeF3pZheLi4bajVzwq1fWW+x3grS188P9OZso="

branches:
  only:
    - master
    - ci
    - coverity_scan
    - /release\/.*$/

before_install:
  - if [ "$TRAVIS_COMPILER" = "clang" ]; then export CXX="clang++"; fi
  - if [ "$TRAVIS_COMPILER" = "gcc" ]; then export CXX="g++"; fi



script:
  - ./bootstrap.py
after_failure: cat ./build/config.log
after_script: TOOLS/travis-rebuild-website

notifications:
  email: false
  irc:
    if: fork = false
    channels:
      - "irc.libera.chat#mpv-devel"
    on_success: change
    on_failure: always

addons:
  coverity_scan:
    project:
      name: "mpv-player/mpv"
      description: "Build submitted via Travis CI"
    notification_email: mpv-team@googlegroups.com
    build_command_prepend: "./bootstrap.py && ./waf configure"
    build_command:   "./waf build"
    branch_pattern: coverity_scan
