name: "Report a Linux Issue"
description: "Create a report for a runtime related Linux Issue"
labels: ["os:linux"]
body:
- type: textarea
  attributes:
      label: "Important Information"
      description: >
          - mpv version
           - Linux Distribution and Version
           - Source of the mpv binary
           - If known which version of mpv introduced the problem
           - Window Manager and version
           - GPU model, driver and version
           - Possible screenshot or video of visual glitches

          If you're not using git master or the latest release, update.
          Releases are listed [here](https://github.com/mpv-player/mpv/releases).
      value: |-
          - mpv version:
          - Linux version:
          - Source:
          - Introduced in version:
          - Window Manager and version:
          - GPU model, driver and version:
  validations:
      required: true
- type: textarea
  attributes:
      label: "Reproduction Steps"
      description: >
          Try to reproduce your issue with `--no-config` first. If it isn't reproducible
          with `--no-config` try to find out which option or script causes your issue.


          If the issue is render performance-related, try to reproduce it with `--no-config
          --profile=fast`, which is designed to work on lower-end mobile devices.


          For decoding performance-related issues, additionally try to enable hardware
          decoding with `--hwdec=yes` or the `Ctrl+h` shortcut.


          Describe the reproduction steps as precise as possible. It's very likely that
          the bug you experience wasn't reproduced by the developer because the workflow
          differs from your own.
  validations:
      required: true
- type: textarea
  attributes:
      label: "Expected Behavior"
      placeholder: "What were you expecting?"
  validations:
      required: true
- type: textarea
  attributes:
      label: "Actual Behavior"
      placeholder: "What happened instead?"
  validations:
      required: true
- type: textarea
  attributes:
      label: "Log File"
      placeholder: "Drag and drop log file here (Don't paste content directly)"
      description: >
          Make a log file with `--gpu-debug --log-file=output.txt`, which is our preferred way, and
          attach it to the issue.


          If you have trouble producing a log file, you can alternatively use `--gpu-debug -v -v`,
          save the terminal output to a file, and attach it to the issue.


          In the case of a crash, please provide a backtrace.


          Without the log file, this issue will be closed for ignoring the issue template.
  validations:
      required: true
- type: textarea
  attributes:
      label: "Sample Files"
      placeholder: "Drag and drop sample files here"
      description: >
          Sample files needed to reproduce this issue can be attached to the issue
          (preferred), or be uploaded to https://0x0.st/ or similar sites.
          (Only needed if the issue cannot be reproduced without it.)
          Do not use garbage like "cloud storage", especially not Google Drive.
- type: checkboxes
  attributes:
      label: "I carefully read all instruction and confirm that I did the following:"
      options:
          - label: "I tested with the latest mpv version to validate that the issue is not already fixed."
            required: true
          - label: "I provided all required information including system and mpv version."
            required: true
          - label: >-
              I produced the log file with the exact same set of files, parameters, and conditions
              used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
            required: true
          - label: >-
              I produced the log file while the behaviors described in "Actual Behavior" were
              actively observed.
            required: true
          - label: "I attached the full, untruncated log file."
            required: true
          - label: "I attached the backtrace in the case of a crash."
            required: true
