name: "Request a new Feature"
description: "Create a request for a new feature"
labels: ["meta:feature-request"]
body:
- type: textarea
  attributes:
      label: "Expected behavior of the wanted feature"
      description: >
          Before requesting a new feature make sure it hasn't been
          [requested yet](https://github.com/mpv-player/mpv/labels/meta%3Afeature-request).
  validations:
      required: true
- type: textarea
  attributes:
      label: "Alternative behavior of the wanted feature"
- type: textarea
  attributes:
      label: "Log File"
      description: >
          Even if you think it's not necessary at first, it might help us later to find
          possible issues. Make a log file made with `-v -v` or `--log-file=output.txt` and
          attach it to the issue.
