name: "Ask a Question"
description: "Ask a question about mpv"
labels: ["meta:question"]
body:
- type: textarea
  attributes:
    label: Question
    description: |
      Don't ask questions about issues, errors or problems you have and instead open
      a proper issue with the right template from the previous selection.

      This template is meant for questions about the workings of mpv, to clarify about
      unspecified behaviour of options or command, or anything else that is not well
      described and needs clarification.

      Before asking a question make sure it hasn't been asked or answered yet.
      https://github.com/mpv-player/mpv/labels/meta%3Aquestion    
  validations:
    required: true

- type: textarea
  attributes:
    label: Log file
    description: |
      Even if you think it's not necessary at first, it might help us later to find
      possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
      it to https://0x0.st/ or attach it to the github issue.
  validations:
    required: false